
spring:
  main:
    #设置无端口启动
    allow-bean-definition-overriding: true
    web-application-type: none

  application:
    name: chat
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

#server:
#  port: 8090

